### ISSUE TITLE
Set Up React Router for Client-Side Routing in React Application

### ISSUE THREAD

**Issue by jps27CSE** [jps27CSE/Gadgets-E-Commerce_React_Django#12]
Description:

Issue Description:
We need to configure and set up React Router in our React application to enable client-side routing. React Router will allow us to create multiple pages and navigate between them without full page reloads, providing a smoother user experience.

Acceptance Criteria:

 Install the React Router package and its dependencies.
 Configure React Router with initial routes and basic navigation.
 Create route components for each page or section of the application.
 Implement client-side navigation between routes using React Router's components (e.g., <Link> or <Route>).
 Ensure that the routing works as expected, and URLs update when navigating between different pages.
 Test the application to verify that routes are functioning correctly.
 Add appropriate routing for any dynamic or parameterized routes, if required.
 Create a Pull Request for review and merge when the routing setup is complete.

**Comment by frs11** [comment]
Please assign this to me
