### ISSUE TITLE
Create Banner Section for Landing Page

### ISSUE THREAD

**Issue by jps27CSE** [jps27CSE/Gadgets-E-Commerce_React_Django#13]
Description:

Issue Description:
We need to design and implement a visually appealing banner section for the landing page of our website. The banner section is a crucial element that captures the attention of visitors and provides a brief introduction to our site's content or purpose.

Acceptance Criteria:

 Design and implement a responsive banner section with an attractive visual layout.
 Include a visually appealing background image or video relevant to our site's theme or content.
 Add a concise and engaging headline that communicates the key message or value proposition of our website.
 Incorporate a call-to-action (CTA) button or link that encourages visitors to take action (e.g., "Learn More," "Sign Up").
 Ensure that the banner section is responsive and visually appealing on various screen sizes and devices.
 Test the banner section to ensure proper functionality and visual consistency across browsers.
 Create a Pull Request for review and merge when the banner section is ready.

**Comment by Ariful2634** [comment]
Please assign it to me
