### ISSUE TITLE
Create Footer Section for Website

### ISSUE THREAD

**Issue by jps27CSE** [jps27CSE/Gadgets-E-Commerce_React_Django#23]
Description:

Issue Description:
We need to design and implement a footer section for our website. The footer is an important component that provides information, navigation, and additional details at the bottom of our web pages.

Acceptance Criteria:

 Design a visually appealing and responsive footer section.
 Include essential information in the footer, such as contact details, links to important pages (e.g., "About Us," "Contact," "Privacy Policy"), and copyright information.
 Ensure that the footer is consistent with the overall design and color scheme of the website.
 Make the footer responsive, so it looks good on various screen sizes and devices.
 Create a Pull Request for review and merge when the footer section is ready.

**Comment by Ariful2634** [comment]
Assigned it to me
