### ISSUE TITLE
Product API using Django

### ISSUE THREAD

**Issue by jps27CSE** [jps27CSE/Gadgets-E-Commerce_React_Django#5]
Issue Description:
We need to develop a RESTful API for managing products in our Django-based web application. This API will allow us to perform (Read) operations on product data.

Acceptance Criteria:

 Set up a Django project if not already done.
 Create a Django app for handling product-related functionality.
 Define a Product model with relevant fields (e.g., name, description, price, etc.).
 Implement API endpoints for creating, reading, updating, and deleting products.
 Implement validation and error handling for the API.
 Create a Pull Request for review and merge when the code is ready.

**Comment by pd28CSE** [comment]
assign me for Django backend API.
