### ISSUE TITLE
Create a Navbar using Tailwind in Frontend (React) 

### ISSUE THREAD

**Issue by jps27CSE** [jps27CSE/Gadgets-E-Commerce_React_Django#7]
Description:

Issue Description:
We need to implement a responsive navigation bar for our React frontend using Tailwind CSS. The navbar should include the following elements:

Site Title: Display the name of our website.
Home: A link to the home page of our site.
Product: A link to the product page of our site.
Login Button: A button/link for users to access the login functionality.

Acceptance Criteria:

 Create a responsive navigation bar using Tailwind CSS.
 Include a site title element.
 Add a "Home" link in the navbar.
 Add a "Product" link in the navbar.
 Implement a login button/link in the navbar.
 Ensure the navbar is visually appealing and responsive for different screen sizes.
 Test the navbar to ensure all links and buttons are functional.
 Ensure the code adheres to best practices and is well-documented.
 Create a Pull Request for review and merge when the navbar is ready.

**Comment by frs11** [comment]
Please assign me this issue. I want to contribute on it
